### ISSUE TITLE
Initial page > 11

### ISSUE THREAD

**Issue by KBepo** [archriss/react-native-image-gallery#9] opened 2017-07-07 23:00 UTC
It doesn't work at all for me. If you set initial page to more than 11 it always displays 12th picture, seems to ignore initial page. How to solve this?

**Comment by Exilz** [comment] 2017-08-17 13:28
Hi,
I can't seem to reproduce this issue, do you have a simple sample of code so I can take a look at it ?

**Comment by chrusart** [comment] 2017-09-05 14:49
First of all I'm glad that someone took it over when maintainer stopped to support it.

Have the same, it all comes from ViewPager. When initialPage > initialListSize + 2 (10 seems to be default for ListView)  it seems the last item is rendered from refs list. Refs list is created in Gallery::renderPage and it's easy to check that renderPage will be invoked 12 times (0..11 index) and if we add initialListSize prop for ListView in ViewPager class than it will be initialListSize + 2.

Thise issue is described here:
https://github.com/ldn0x7dc/react-native-view-pager/issues/4

Sure you can set initialListSize in ViewPager but for large lists will not work.

There are other bugs as well that needs to be fixed or merged PRs.

I also will need to merge few fixes to ViewPager cause first crash on my list is caused by:
https://github.com/ldn0x7dc/react-native-view-pager/pull/6

**Comment by Exilz** [comment] 2017-09-05 15:55
Hi @chrusart, thanks for the explanation on this problem.

I would need to take a deeper look to figure everything out, but it seems you've understood this issue already.

To be honest, I was planning on getting rid of the multiple dependencies to @ldn0x7dc packages, since he doesn't seem to be active on these repos either.

The best thing would be to copy each of their content and to provide them directly in react-native-image-gallery 's codebase. That way, we won't have to wait for him to merge these PRs.

If you're already familiar with react-native-view-pager 's code, I'd love you to make a PR on our repo with all you need to update from the dependency and add it as a file here. It will make future modifications much easier for us.

**Comment by chrusart** [comment] 2017-09-08 12:38
PR #13

**Comment by Exilz** [comment] 2017-09-13 08:45
Hi @KBepo, @chrusart 's PR fixed it nicely. Stay tuned for the release candidate of the next version of the module.

**Closed by Exilz** 2017-09-13 08:45 UTC

**Comment by alainib** [comment] 2018-01-16 13:23
i still have this error, how to fix it please? 

my version
react-native-image-gallery  2.1.5
react-native   0.51.0

thanks

**Comment by rskull** [comment] 2018-01-22 06:59
I got same issue.

Android
react-native-image-gallery v2.1.5
react-native 0.46.4

If you set initial page to more than 11 it always displays 10th picture, but v2.1.4 is working.

**Comment by jing-wu** [comment] 2018-01-29 05:59
Same issue.

Android Nexus 6P
react-native-image-gallery v2.1.5
react-native 0.52.0

Always displaying 10th image when it has more than 11 images.
