### ISSUE TITLE
[Android] initialPage not implemented in 2.0.0

### ISSUE THREAD

**Issue by vbuch** [archriss/react-native-image-gallery#20] opened 2017-09-20 12:10 UTC
Used to use the `initialPage` prop in 1.x. I am sorry to see that it is not implemented in v2.

**Comment by Exilz** [comment] 2017-09-20 12:59
It is implemented, are you having troubles with it ?

**Comment by vbuch** [comment] 2017-09-20 13:03
Yup. Keeps me on first page. Still, I'll continue with my fork. Tried to check if switching to 2.0.0 and reapplying my changes will be an option for me. Not the case. Won't be able to provide more info. If you are sure it is implemented and working in v2, I will close the issue.

**Comment by Exilz** [comment] 2017-09-20 13:10
It works for me on the demo with version `2.0.0`.

![](https://puu.sh/xEoHY/5f52f5c422.png)

Are you doing something specific to set your initialPage ? Could you try using a fixed number, just to see if it works ?

By the way, what are you missing on this plugin that makes you keep using your fork ?

**Comment by vbuch** [comment] 2017-09-20 13:13
Can't give it a try currently. What I have additional to what was already there is the ability to show low res images while high res images are still loading.

**Comment by vanhiepdam** [comment] 2017-09-21 08:45
i had also this problem. I set initialPage to 3, but it still displayed fist element in the array
After swiped to the next or previous image, it displayed the image at 4 or 2. Hope you to fix it!

**Comment by Exilz** [comment] 2017-09-21 10:02
Can you send me some of your code ? I'm having troubles reproducing this issue.

**Comment by vbuch** [comment] 2017-09-21 11:13
Just switched my fork of v1 to use your ViewPager from v2 and I can reproduce it. It's something in the ViewPager.
So I have 3 images. If I try to go to page 2 (0-based), image 1 is shown to me. Swipe back to the first image (where it is shown again), then again to image 2 and all is fine.

**Comment by chrusart** [comment] 2017-09-21 13:25
I can confirm, didn't have time to check if it's on my side and didn't get earlier with this issue.

**Comment by vanhiepdam** [comment] 2017-09-22 03:44
>  <Gallery
         style={{ flex: 1, backgroundColor: 'black' }}
         images={this.state.imageList}
         initialPage={this.state.initialImage}
 />
@Exilz  this is a snippet of my code

**Comment by vanhiepdam** [comment] 2017-09-22 04:00
Could u explain this prop to me in more details?

onPageSelected | Fired with the index of page that has been selected

**Comment by Exilz** [comment] 2017-09-22 07:49
You pass a function that receives as its argument the index of the page that you've scrolled to.

I have no time to take a look at this `initialPage` bug for the moment, I'll look into it ASAP.

**Comment by vanhiepdam** [comment] 2017-09-22 07:52
Ok bro @Exilz. Thanks for your support. Have a good day

**Comment by chrusart** [comment] 2017-09-22 08:57
If u just swipe a few pixels and correct image appears it's something with FlatList refreshing after scrolling to item without animation:
https://github.com/facebook/react-native/issues/15634

**Comment by vbuch** [comment] 2017-09-22 09:26
If anyone of you is currently debugging it, you could try triggering the
animation after interactions are done. InteractionManager.runAfter...

На пт, 22.09.2017 г., 11:57 chrusart <notifications@github.com> написа:

**Comment by vanhiepdam** [comment] 2017-09-22 09:57
i thought it will make app slow

**Comment by davidpaulsson** [comment] 2017-10-04 12:00
Can confirm this. Any progress or suggestions on how to fix it? Just nudging the image will re-render to show the correct index.

**Comment by vbuch** [comment] 2017-10-04 12:35
Looking at it currently. Will let you know if there is any progress @davidpaulsson

**Comment by vbuch** [comment] 2017-10-04 14:19
I think I have the solution. Will need someone to test it with iOS so great @davidpaulsson joined here :-) I'll write again once I'm done with commiting.

**Comment by vbuch** [comment] 2017-10-04 14:41
@davidpaulsson @chrusart @vanhiepdam @Exilz here's a PR

**Comment by Exilz** [comment] 2017-10-04 14:46
@vbuch I'm happy to see you've dug deep into this problem. I didn't know this was specific to android, this explains why I couldn't reproduce it on the simulator.

I'll try to review this ASAP, it looks like you've changed quite a few things and cleaned up some bulk, great ! We should test for regressions and not just this issue since so much code changed.

**Comment by vbuch** [comment] 2017-10-04 14:49
Once you get to read it, you'll see the changes are not that much. Still, hope @davidpaulsson can test it on both Android and iPhone.

**Comment by davidpaulsson** [comment] 2017-10-04 19:39
Sure, I’ll test it. But I have some weird bug in my app atm that I need to resolve first before I can test (images don’t show, but just sometimes. if I change something in the code hot-reload rerenders the Gallery and the image shows after that).

**Comment by Haideralee** [comment] 2017-10-05 12:42
@Exilz **initialPage** is not working with ** imageComponent**. can you please show any example. 
i am using xcode simulator.

Thanks

**Comment by vbuch** [comment] 2017-10-05 12:51
@Haideralee you maybe missed the fact that `imageComponent` needs to be a rendering function. `(props, dimensions) => {}`

**Comment by Exilz** [comment] 2017-10-05 13:41
Fixed in `2.1.1`, #26, #24

**Closed by Exilz** 2017-10-05 13:41 UTC

**Comment by Haideralee** [comment] 2017-10-05 14:35
@vbuch i added a render function of imageComponent but the issue is it's also show first image for the first time. 
example i have 5 images and i select 3th image so it's should show 3 index image on the cover but it's always show 0 index image on the cover.

**Comment by vbuch** [comment] 2017-10-05 15:12
@Haideralee I can't help much for iOS. Sorry.
