### ISSUE TITLE
Click Handler

### ISSUE THREAD

**Issue by yasinugrl** [archriss/react-native-image-gallery#41] opened 2018-01-02 09:29 UTC
Can this library provide click handler for go next image? Or is there any way to make this?

**Comment by Exilz** [comment] 2018-01-03 08:20
Hi, are you looking for a method to slide to a specific slide ? I'm not sure I understand what you mean by "handler".

**Comment by slorber** [comment] 2018-01-04 13:20
Hi,

I need something similar: ability to press next/previous arrows

**Comment by Exilz** [comment] 2018-01-04 13:21
I'm gonna close this issue as it is a duplicate of #37

**Closed by Exilz** 2018-01-04 13:21 UTC
